-- MySQL Script generated by MySQL Workbench
-- Thu May 30 15:56:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema beeogarden
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beeogarden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beeogarden` DEFAULT CHARACTER SET utf8 ;
USE `beeogarden` ;

-- -----------------------------------------------------
-- Table `beeogarden`.`Chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`Chat` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`Chat` (
  `id_chat` INT NOT NULL AUTO_INCREMENT,
  `nome_chat` VARCHAR(50) NOT NULL,
  `date_creation_chat` DATETIME NOT NULL,
  `ref_Utilizador` INT NOT NULL,
  `ref_Espaco` INT NOT NULL,
  PRIMARY KEY (`id_chat`),
  INDEX `fk_Chat_Utilizador_idx` (`ref_Utilizador` ASC) ,
  INDEX `fk_Chat_Espaco1_idx` (`ref_Espaco` ASC) ,
  CONSTRAINT `fk_Chat_Utilizador`
    FOREIGN KEY (`ref_Utilizador`)
    REFERENCES `beeogarden`.`Utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_Espaco1`
    FOREIGN KEY (`ref_Espaco`)
    REFERENCES `beeogarden`.`Espaco` (`id_espaco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`Espaco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`Espaco` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`Espaco` (
  `id_espaco` INT NOT NULL AUTO_INCREMENT,
  `nome_espaco` VARCHAR(200) NOT NULL,
  `morada` VARCHAR(100) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `localidade` VARCHAR(50) NOT NULL,
  `dimensao` VARCHAR(50) NOT NULL,
  `ajuda` TINYINT NOT NULL,
  `ref_Utilizador` INT NOT NULL,
  PRIMARY KEY (`id_espaco`),
  INDEX `fk_Espaco_Utilizador1_idx` (`ref_Utilizador` ASC) ,
  CONSTRAINT `fk_Espaco_Utilizador1`
    FOREIGN KEY (`ref_Utilizador`)
    REFERENCES `beeogarden`.`Utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`Estado_Mensagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`Estado_Mensagem` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`Estado_Mensagem` (
  `id_estado_mensagem` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_mensagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`Mensagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`Mensagens` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`Mensagens` (
  `id_mensagens` INT NOT NULL,
  `Mensagem` TEXT NOT NULL,
  `date_creation_message` DATETIME NOT NULL,
  `estado_mensagem` INT NOT NULL,
  `ref_Chat` INT NOT NULL,
  `ref_Estado_Mensagem` INT NOT NULL,
  PRIMARY KEY (`id_mensagens`),
  INDEX `fk_Mensagens_Chat1_idx` (`ref_Chat` ASC) ,
  INDEX `fk_Mensagens_Estado_Mensagem1_idx` (`ref_Estado_Mensagem` ASC) ,
  CONSTRAINT `fk_Mensagens_Chat1`
    FOREIGN KEY (`ref_Chat`)
    REFERENCES `beeogarden`.`Chat` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensagens_Estado_Mensagem1`
    FOREIGN KEY (`ref_Estado_Mensagem`)
    REFERENCES `beeogarden`.`Estado_Mensagem` (`id_estado_mensagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`Produto` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(200) NOT NULL,
  `descricao_produto` TEXT NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`Utilizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`Utilizador` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`Utilizador` (
  `id_utilizador` INT NOT NULL AUTO_INCREMENT,
  `utilizador` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(256) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `biografia` MEDIUMTEXT NULL,
  `foto_perfil` BLOB NULL,
  `beeopoints` INT NOT NULL,
  `ref_roles` INT NOT NULL,
  `ref_genero` INT NOT NULL,
  PRIMARY KEY (`id_utilizador`),
  INDEX `fk_Utilizador_roles1_idx` (`ref_roles` ASC) ,
  INDEX `fk_Utilizador_genero1_idx` (`ref_genero` ASC) ,
  CONSTRAINT `fk_Utilizador_roles1`
    FOREIGN KEY (`ref_roles`)
    REFERENCES `beeogarden`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilizador_genero1`
    FOREIGN KEY (`ref_genero`)
    REFERENCES `beeogarden`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`compras` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `preco_total` FLOAT NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `ref_Utilizador` INT NOT NULL,
  `ref_Produto` INT NOT NULL,
  PRIMARY KEY (`id_compras`),
  INDEX `fk_compras_Utilizador1_idx` (`ref_Utilizador` ASC) ,
  INDEX `fk_compras_Produto1_idx` (`ref_Produto` ASC) ,
  CONSTRAINT `fk_compras_Utilizador1`
    FOREIGN KEY (`ref_Utilizador`)
    REFERENCES `beeogarden`.`Utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_Produto1`
    FOREIGN KEY (`ref_Produto`)
    REFERENCES `beeogarden`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`genero` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `genero_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`info` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`info` (
  `id_info` INT NOT NULL AUTO_INCREMENT,
  `nome_info` VARCHAR(100) NOT NULL,
  `info_descricao` MEDIUMTEXT NOT NULL,
  `info_imagem` BLOB NOT NULL,
  `ref_Utilizador` INT NOT NULL,
  PRIMARY KEY (`id_info`),
  INDEX `fk_info_Utilizador1_idx` (`ref_Utilizador` ASC) ,
  CONSTRAINT `fk_info_Utilizador1`
    FOREIGN KEY (`ref_Utilizador`)
    REFERENCES `beeogarden`.`Utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`reports` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`reports` (
  `id_reports` INT NOT NULL AUTO_INCREMENT,
  `data_report` DATETIME NOT NULL,
  `ref_Utilizador` INT NOT NULL,
  `ref_Espaco` INT NOT NULL,
  PRIMARY KEY (`id_reports`),
  INDEX `fk_reports_Utilizador1_idx` (`ref_Utilizador` ASC) ,
  INDEX `fk_reports_Espaco1_idx` (`ref_Espaco` ASC) ,
  CONSTRAINT `fk_reports_Utilizador1`
    FOREIGN KEY (`ref_Utilizador`)
    REFERENCES `beeogarden`.`Utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_Espaco1`
    FOREIGN KEY (`ref_Espaco`)
    REFERENCES `beeogarden`.`Espaco` (`id_espaco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beeogarden`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beeogarden`.`roles` ;

CREATE TABLE IF NOT EXISTS `beeogarden`.`roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `roles_descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
